[project]
name = "molecular-docking-pymol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gemmi>=0.7.5",
    "jupyter>=1.1.1",
    "meeko>=0.7.1",
    "pandas>=3.0.3",
    "prody>=2.6.1",
    "pymol-open-source>=3.2.0a0",
    "rdkit>=2026.3.2",
    "requests>=2.34.2",
    "scipy>=1.17.1",
]
